version: "3.8"

networks:
  shared-net:
    external: true
    name: shared-net

services:
  frontend:
    build: .
    container_name: codevi-frontend
    restart: always
    ports:
      - "18080:80"
    volumes:
      # 호스트의 SSL 인증서 경로를 컨테이너와 연결 (매우 중요)
      - /etc/letsencrypt/live/selab-swv.store:/etc/nginx/ssl:ro
    networks:
      - shared-net